# Generated by Django 4.2.1 on 2023-05-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(default='Utown', max_length=30)),
                ('closed', models.BooleanField(default=False)),
                ('total_pax', models.IntegerField(default=10)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
