# Generated by Django 4.2.1 on 2023-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_venues_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='host',
            field=models.CharField(default='Admin', max_length=50, unique=True),
        ),
    ]
