# Generated by Django 4.2.1 on 2023-05-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_venue_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='host',
            field=models.CharField(default='Admin', max_length=50, unique=True),
        ),
    ]
